---
title: 'Question 1: Systematic AI Fund'
author: "Andrew Hyde"
date: '2022-11-26'
output:
  pdf_document: default
  html_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.width = 6, fig.height = 5, fig.pos="H", fig.pos = 'H')
# Note: Include = FALSE implies the code is executed, but not printed in your pdf.
# warning and message = FALSE implies ugly messages and warnings are removed from your pdf.
# These should be picked up when you execute the command chunks (code sections below) in your rmd, not printed in your paper!

# Lets load in example data, and see how this can be stored and later called from your 'data' folder.
library(tidyverse)
ASISA <- read_rds("data/ASISA.rds")
BM <- read_rds("data/Capped_SWIX.rds")
AI_Fund <- read_rds("data/AI_Max_Fund.rds")

```


<!-- ############################## -->
<!-- # Start Writing here: -->
<!-- ############################## -->

# Introduction \label{Introduction}


```{r}

# this works if calc individually firms
q1_data_combined <- left_join(msci %>% 
                        spread(Name, Return) %>%
                        select(date, MSCI_ACWI, MSCI_RE),
                    
                        bonds %>% spread(Name, Return) %>% select(date, US_10Yr),
                                by = "date") %>% 
    
                    left_join(.,
                            comms %>% spread(Name, Return) %>% select(date, Bcom_Index),
                                by = "date" )


```








```{r}

```


